### PR TITLE
Fix FastAsyncWorldEdit.svg

### PR DESCRIPTION
**Pull request by PierreSchwang**
Simplify FastAsyncWorldEdit.svg and remove rendering errors due to translucent background.
- Draws the dark-blue handle of the axe using one path instead of two separate ones to ensure constant background. 
- Fixes dark blue shadows not aligned properly.
- Remove transform and clip-path shenanigans 

```[tasklist]
### Submitter Checklist
- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [x] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

### CODE REVIEW

**Comment by NotMyFault** [comment]
LGTM, but what's with

Screenshot 2023-09-11 at 16 37 55

at the front of the axe? Or am I going nuts?

**Comment by PierreSchwang** [comment]
> LGTM, but what's with
> 
> 
> 
> Screenshot 2023-09-11 at 16 37 55
> 
> 
> 
> at the front of the axe? Or am I going nuts?

Oic, haven't changed anything there

**Comment by PierreSchwang** [comment]
@NotMyFault lmk if it looks better now

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Pull request merged**
